/**
 * Primitive tokens — context-free foundational values (color palettes, radius,
 * spacing, typography). These carry no meaning on their own; semantic tokens
 * map onto them. Layer 1 of 3.
 */
import type { TokenNode } from './types';

export const neutral = {
  0: '#ffffff',
  50: '#f8fafc',
  100: '#f1f5f9',
  200: '#e2e8f0',
  300: '#cbd5e1',
  400: '#94a3b8',
  500: '#64748b',
  600: '#475569',
  700: '#334155',
  800: '#1e293b',
  900: '#0f172a',
  950: '#020617',
};

export const blue = {
  50: '#eff6ff',
  100: '#dbeafe',
  200: '#bfdbfe',
  300: '#93c5fd',
  400: '#60a5fa',
  500: '#3b82f6',
  600: '#2563eb',
  700: '#1d4ed8',
  800: '#1e40af',
  900: '#1e3a8a',
  950: '#172554',
};

/** Violet — the far end of the "generated by AI" gradient (red -> violet). */
export const violet = {
  50: '#f5f3ff',
  100: '#ede9fe',
  200: '#ddd6fe',
  300: '#c4b5fd',
  400: '#a78bfa',
  500: '#8b5cf6',
  600: '#7c3aed',
  700: '#6d28d9',
  800: '#5b21b6',
  900: '#4c1d95',
  950: '#2e1065',
};

export const cyan = {
  50: '#ecfeff',
  100: '#cffafe',
  200: '#a5f3fc',
  300: '#67e8f9',
  400: '#22d3ee',
  500: '#06b6d4',
  600: '#0891b2',
  700: '#0e7490',
  800: '#155e75',
  900: '#164e63',
  950: '#083344',
};

export const emerald = {
  100: '#d1fae5',
  400: '#34d399',
  500: '#10b981',
  600: '#059669',
  950: '#022c22',
};

export const amber = {
  100: '#fef3c7',
  400: '#fbbf24',
  500: '#f59e0b',
  600: '#d97706',
  950: '#451a03',
};

export const red = {
  50: '#fef2f2',
  100: '#fee2e2',
  200: '#fecaca',
  300: '#fca5a5',
  400: '#f87171',
  500: '#ef4444',
  600: '#dc2626',
  700: '#b91c1c',
  800: '#991b1b',
  900: '#7f1d1d',
  950: '#450a0a',
};

export const borderRadius = {
  none: '0',
  sm: '6px',
  md: '8px',
  lg: '12px',
  xl: '16px',
  full: '9999px',
};

export const font = {
  family:
    "'Inter', ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
  familyMono:
    "'JetBrains Mono', ui-monospace, 'SF Mono', Menlo, Consolas, monospace",
};

/** The complete primitive layer bundled for a preset. */
export const primitive: Record<string, TokenNode> = {
  neutral,
  blue,
  violet,
  cyan,
  emerald,
  amber,
  red,
  borderRadius,
  font,
};
