import {
  InjectionToken,
  computed,
  inject,
  isSignal,
  type Signal,
} from '@angular/core';
import type { PlanStepStatus, ToolCallStatus } from './types';

/**
 * Every fixed user-facing string rendered by the components (status badges,
 * action buttons, aria-labels, hints). Strings that are already component
 * inputs (`title`, `placeholder`, `emptyTitle`, …) are not listed here — those
 * stay consumer-provided per instance.
 */
export interface AgtLabels {
  chat: {
    /** aria-label of the "agent is thinking" indicator. */
    thinking: string;
    /** aria-label of the composer send button. */
    sendMessage: string;
  };
  reasoning: {
    /** Shimmering label while reasoning streams. */
    thinking: string;
    /** Trigger label once reasoning finished and a duration is known. */
    thoughtFor: (seconds: number) => string;
    /** Trigger label when no duration is available. */
    thoughtForUnknown: string;
  };
  toolCall: {
    /** Status badge texts. */
    statuses: Record<ToolCallStatus, string>;
    /** Muted text while running without progress steps. */
    working: string;
    /** Detail section label on success. */
    result: string;
    /** Detail section label on error. */
    error: string;
  };
  plan: {
    /** Screen-reader status appended to each step. */
    statuses: Record<PlanStepStatus, string>;
  };
  approval: {
    approve: string;
    reject: string;
    edit: string;
    /** Resolved-state badges. */
    approved: string;
    rejected: string;
  };
  summary: {
    /** Provenance badge. */
    generatedByAi: string;
    /** aria-label of the regenerate action. */
    regenerate: string;
    /** aria-label of the copy action. */
    copy: string;
    /** aria-label of the copy action right after copying. */
    copied: string;
    /** Screen-reader status while the skeleton is shown. */
    generating: string;
  };
  suggestion: {
    /** Badge on an accepted, AI-filled value. */
    aiBadge: string;
    /** Badge once the human edited an accepted AI value. */
    editedByHuman: string;
    /** aria-labels of the accept / reject controls. */
    acceptAria: string;
    rejectAria: string;
    /** First part of the hint under a pending suggestion. */
    aiSuggestion: string;
    /** Confidence part of the hint, from a 0–100 percentage. */
    confidence: (pct: number) => string;
    /** Keyboard hint. */
    tabToAccept: string;
  };
  sidebar: {
    /** aria-label of the close button. */
    close: string;
    /** aria-label of the FAB. */
    open: string;
    /** aria-label of the FAB when the badge shows a count. */
    openWithCount: (count: number) => string;
  };
  codeBlock: {
    /** Copy button text and its post-copy feedback. */
    copy: string;
    copied: string;
    /** aria-label of the copy button. */
    copyAria: string;
  };
}

/** The built-in English strings — the exact defaults the components ship with. */
export const AGT_DEFAULT_LABELS: AgtLabels = {
  chat: {
    thinking: 'Thinking',
    sendMessage: 'Send message',
  },
  reasoning: {
    thinking: 'Thinking…',
    thoughtFor: (seconds) =>
      `Thought for ${seconds} second${seconds === 1 ? '' : 's'}`,
    thoughtForUnknown: 'Thought for a few seconds',
  },
  toolCall: {
    statuses: { running: 'Running', success: 'Completed', error: 'Error' },
    working: 'Working…',
    result: 'Result',
    error: 'Error',
  },
  plan: {
    statuses: {
      pending: 'Pending',
      active: 'In progress',
      done: 'Completed',
      error: 'Failed',
    },
  },
  approval: {
    approve: 'Approve',
    reject: 'Reject',
    edit: 'Edit',
    approved: 'Approved',
    rejected: 'Rejected',
  },
  summary: {
    generatedByAi: 'Generated by AI',
    regenerate: 'Regenerate summary',
    copy: 'Copy summary',
    copied: 'Copied',
    generating: 'Generating summary…',
  },
  suggestion: {
    aiBadge: 'AI',
    editedByHuman: 'Edited by human',
    acceptAria: 'Accept suggestion',
    rejectAria: 'Reject suggestion',
    aiSuggestion: 'AI suggestion',
    confidence: (pct) => `${pct}% confidence`,
    tabToAccept: 'Tab to accept',
  },
  sidebar: {
    close: 'Close agent panel',
    open: 'Open agent panel',
    openWithCount: (count) => `Open agent panel, ${count} new`,
  },
  codeBlock: {
    copy: 'Copy',
    copied: 'Copied',
    copyAria: 'Copy code',
  },
};

/** Consumers may provide a static object or a Signal (for live language switching). */
export type AgtLabelsInput = AgtLabels | Signal<AgtLabels>;

export const AGT_LABELS = new InjectionToken<AgtLabelsInput>('AGT_LABELS', {
  factory: () => AGT_DEFAULT_LABELS,
});

/**
 * Normalized reactive view over {@link AGT_LABELS} — components call
 * `labels = injectLabels()` and read `labels().plan.statuses.done`.
 */
export function injectLabels(): Signal<AgtLabels> {
  const provided = inject(AGT_LABELS);
  return isSignal(provided) ? provided : computed(() => provided);
}
