import type { Localized } from '../i18n/i18n';

const EN = {
  eyebrow: 'Getting started',
  title: 'Provenance',
  lead: 'In regulated products, a user must always be able to tell what a person wrote from what an AI generated. agentic makes that a default: every AI-generated element carries the same accent and label — one consistent signal across the whole kit.',
  accent: {
    title: 'One accent, one meaning',
    body: 'Provenance isn\'t a component — it\'s a pattern. A single design token, <code>--agt-ai-color</code> (and its gradient <code>--agt-ai-gradient</code>), marks everything the AI touched: the streaming cursor, the "Generated by AI" label, the confidence badge. Restyle that one token and the AI signal updates everywhere. It stays deliberately distinct from your primary / brand colour, so "AI" never blends into "interactive".',
  },
  summary: {
    title: 'In a summary',
    body: 'An AI-written summary is labelled and can be regenerated — never mistaken for a human note.',
  },
  field: {
    title: 'In a form field',
    body: 'A suggestion appears as ghost text with a confidence badge. Accept it and the value is marked AI; edit it and it flips to "edited by human" — the provenance follows the value, which is exactly what an auditor needs.',
  },
  chat: {
    title: 'In chat',
    body: "The agent's replies stream under the same accent, with a collapsible reasoning trace and a live cursor — it's always clear which turns came from the model.",
  },
  why: {
    title: 'Why it matters',
    body: '"The AI did it" is not an acceptable answer in fintech, KYC or legal workflows. Clear provenance is what lets a reviewer trust — and take responsibility for — an agent\'s output. agentic gives you the UI building blocks; compliance itself is your product\'s job.',
  },
};

export const PROVENANCE_I18N: Localized<typeof EN> = {
  en: EN,
  es: {
    eyebrow: 'Primeros pasos',
    title: 'Procedencia',
    lead: 'En productos regulados, el usuario siempre debe poder distinguir lo que escribió una persona de lo que generó una IA. agentic lo convierte en el comportamiento por defecto: cada elemento generado por IA lleva el mismo acento y la misma etiqueta — una señal consistente en todo el kit.',
    accent: {
      title: 'Un acento, un significado',
      body: 'La procedencia no es un componente — es un patrón. Un único design token, <code>--agt-ai-color</code> (y su gradiente <code>--agt-ai-gradient</code>), marca todo lo que la IA tocó: el cursor de streaming, la etiqueta "Generado por IA", el badge de confianza. Restiliza ese único token y la señal de IA se actualiza en todas partes. Se mantiene deliberadamente distinto de tu color primario / de marca, para que "IA" nunca se confunda con "interactivo".',
    },
    summary: {
      title: 'En un resumen',
      body: 'Un resumen escrito por IA queda etiquetado y puede regenerarse — nunca se confunde con una nota humana.',
    },
    field: {
      title: 'En un campo de formulario',
      body: 'La sugerencia aparece como texto fantasma con un badge de confianza. Acéptala y el valor queda marcado como IA; edítala y pasa a "editado por humano" — la procedencia sigue al valor, que es exactamente lo que necesita un auditor.',
    },
    chat: {
      title: 'En el chat',
      body: 'Las respuestas del agente llegan en streaming bajo el mismo acento, con una traza de razonamiento plegable y un cursor en vivo — siempre queda claro qué turnos vinieron del modelo.',
    },
    why: {
      title: 'Por qué importa',
      body: '"Lo hizo la IA" no es una respuesta aceptable en fintech, KYC ni en flujos legales. Una procedencia clara es lo que permite a un revisor confiar en el resultado de un agente — y asumir la responsabilidad de él. agentic te da los bloques de UI; el compliance en sí es responsabilidad de tu producto.',
    },
  },
};
