import type { Localized } from '../i18n/i18n';

const EN = {
  eyebrow: 'Getting started',
  title: 'Theming',
  lead: 'Every component is painted with a 3-layer token system — <strong>primitive → semantic → component</strong> — compiled to CSS custom properties. Swap the preset or override any token and the whole library recolors, no CSS forking. Try it live: these controls restyle this entire site at runtime.',
  playground: {
    title: 'Playground',
    intro:
      'Pick a preset, an AI accent and a corner radius. Changes apply globally, instantly.',
    presetLabel: 'Preset',
    accentLabel: 'AI accent',
    radiusLabel: 'Radius',
    reset: 'Reset',
    presetDefaultAria: 'Preset default accent',
    presetDefaultTitle: 'Preset default',
    accents: {
      violet: 'Violet',
      blue: 'Blue',
      emerald: 'Emerald',
      rose: 'Rose',
      amber: 'Amber',
    },
    radii: {
      sharp: 'Sharp',
      default: 'Default',
      rounded: 'Rounded',
    },
  },
  config: {
    title: 'Configure a preset',
    body: 'Choose a built-in preset, or build your own by merging overrides onto one with <code>definePreset()</code> — this is what "restyle outside of ours" means.',
  },
  runtime: {
    title: 'Restyle at runtime',
    body: 'Inject <code>AgenticThemeService</code> to swap presets, merge token overrides or toggle dark mode after bootstrap — exactly what the playground above does.',
  },
  tokens: {
    title: 'Key semantic tokens',
    intro:
      'Semantic tokens reference primitives and compile to these CSS variables.',
    headers: {
      token: 'Token',
      css: 'CSS variable',
      desc: 'Description',
    },
    descs: {
      'primary.color': 'Primary action colour (buttons, links, user bubble).',
      'ai.color':
        'AI/agent accent — cursor, provenance, "generated by AI" marks.',
      'ai.gradient':
        'Signature gradient for AI surfaces (summary accent, FAB).',
      'content.background': 'Base surface behind panels and cards.',
      'content.color': 'Default foreground text colour.',
      'radius.lg': 'Large corner radius (bubbles, cards).',
      'state.success.color': 'Success state (verified, tool-call success).',
      'state.danger.color': 'Danger state (flagged, errors, badges).',
    },
  },
};

export const THEMING_I18N: Localized<typeof EN> = {
  en: EN,
  es: {
    eyebrow: 'Primeros pasos',
    title: 'Theming',
    lead: 'Cada componente se pinta con un sistema de tokens de 3 capas — <strong>primitivo → semántico → componente</strong> — compilado a propiedades CSS personalizadas. Cambia el preset o sobrescribe cualquier token y toda la librería se recolorea, sin forkear el CSS. Pruébalo en vivo: estos controles restilizan todo este sitio en tiempo de ejecución.',
    playground: {
      title: 'Playground',
      intro:
        'Elige un preset, un acento de IA y un radio de esquinas. Los cambios se aplican globalmente, al instante.',
      presetLabel: 'Preset',
      accentLabel: 'Acento de IA',
      radiusLabel: 'Radio',
      reset: 'Restablecer',
      presetDefaultAria: 'Acento por defecto del preset',
      presetDefaultTitle: 'Por defecto del preset',
      accents: {
        violet: 'Violeta',
        blue: 'Azul',
        emerald: 'Esmeralda',
        rose: 'Rosa',
        amber: 'Ámbar',
      },
      radii: {
        sharp: 'Recto',
        default: 'Por defecto',
        rounded: 'Redondeado',
      },
    },
    config: {
      title: 'Configura un preset',
      body: 'Elige un preset integrado, o construye el tuyo fusionando overrides sobre uno con <code>definePreset()</code> — esto es lo que significa "restilizar más allá de lo que traemos de serie".',
    },
    runtime: {
      title: 'Restiliza en tiempo de ejecución',
      body: 'Inyecta <code>AgenticThemeService</code> para cambiar de preset, fusionar overrides de tokens o alternar el modo oscuro después del bootstrap — exactamente lo que hace el playground de arriba.',
    },
    tokens: {
      title: 'Tokens semánticos clave',
      intro:
        'Los tokens semánticos referencian primitivos y se compilan a estas variables CSS.',
      headers: {
        token: 'Token',
        css: 'Variable CSS',
        desc: 'Descripción',
      },
      descs: {
        'primary.color':
          'Color de la acción primaria (botones, enlaces, burbuja del usuario).',
        'ai.color':
          'Acento de IA/agente — cursor, procedencia, marcas de "generado por IA".',
        'ai.gradient':
          'Gradiente distintivo de las superficies de IA (acento del resumen, FAB).',
        'content.background': 'Superficie base detrás de paneles y tarjetas.',
        'content.color': 'Color de texto por defecto.',
        'radius.lg': 'Radio de esquina grande (burbujas, tarjetas).',
        'state.success.color':
          'Estado de éxito (verificado, tool-call con éxito).',
        'state.danger.color': 'Estado de peligro (marcado, errores, badges).',
      },
    },
  },
};
