import { TestBed } from '@angular/core/testing';
import { beforeEach, describe, expect, it } from 'vitest';
import { AgtSummary } from './agt-summary';

function render(inputs: Record<string, unknown>) {
  const fixture = TestBed.createComponent(AgtSummary);
  for (const [key, value] of Object.entries(inputs)) {
    fixture.componentRef.setInput(key, value);
  }
  fixture.detectChanges();
  return fixture;
}

describe('AgtSummary', () => {
  beforeEach(() => TestBed.configureTestingModule({}));

  it('renders the AI-provenance label, markdown content and two actions when loaded', () => {
    const el = render({ title: 'Case summary', content: 'A **short** summary.' })
      .nativeElement as HTMLElement;
    expect(el.querySelector('.agt-summary__provenance')?.textContent).toContain('Generated by AI');
    expect(el.textContent).toContain('Case summary');
    expect(el.innerHTML).toContain('<strong>short</strong>');
    expect(el.querySelectorAll('.agt-summary__action').length).toBe(2);
  });

  it('shows the skeleton (and hides content) while loading', () => {
    const el = render({ content: 'hidden', loading: true }).nativeElement as HTMLElement;
    expect(el.querySelector('.agt-summary__skeleton')).toBeTruthy();
    expect(el.querySelector('agt-stream-text')).toBeNull();
    expect(el.querySelector('[role="status"]')?.textContent).toContain('Generating');
  });

  it('emits regenerate when the regenerate action is clicked', () => {
    const fixture = render({ content: 'x' });
    let emitted = false;
    fixture.componentInstance.regenerate.subscribe(() => (emitted = true));
    (fixture.nativeElement.querySelectorAll('.agt-summary__action')[0] as HTMLButtonElement).click();
    expect(emitted).toBe(true);
  });
});
