import { ChangeDetectionStrategy, Component, input, output, signal } from '@angular/core';
import { AgtStreamText, type StreamSpeed } from '../chat/agt-stream-text';

/**
 * A card for AI-generated summaries. Clearly marked as AI content ("Generated by
 * AI" provenance), with regenerate + copy actions and a skeleton while loading.
 * Content is rendered as markdown and can stream in.
 *
 * ```html
 * <agt-summary title="Case summary" [content]="summary" [loading]="isGenerating" (regenerate)="regen()" />
 * ```
 */
@Component({
  selector: 'agt-summary',
  imports: [AgtStreamText],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'agt-summary' },
  template: `
    <div class="agt-summary__head">
      <span class="agt-summary__provenance">
        <svg viewBox="0 0 24 24" width="13" height="13" aria-hidden="true">
          <path fill="currentColor" d="M12 2l2.2 5.8L20 10l-5.8 2.2L12 18l-2.2-5.8L4 10l5.8-2.2z" />
        </svg>
        Generated by AI
      </span>
      @if (title()) {
        <span class="agt-summary__title">{{ title() }}</span>
      }
      <span class="agt-summary__spacer"></span>
      <div class="agt-summary__actions">
        <button
          type="button"
          class="agt-summary__action"
          [disabled]="loading()"
          aria-label="Regenerate summary"
          (click)="regenerate.emit()"
        >
          <svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true">
            <path fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" d="M20 11a8 8 0 1 0-1.6 4.9M20 5v6h-6" />
          </svg>
        </button>
        <button
          type="button"
          class="agt-summary__action"
          [disabled]="loading() || !content()"
          [attr.aria-label]="copied() ? 'Copied' : 'Copy summary'"
          (click)="copy()"
        >
          @if (copied()) {
            <svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true">
              <path fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" d="m5 12 4 4 10-10" />
            </svg>
          } @else {
            <svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true">
              <rect x="9" y="9" width="11" height="11" rx="2" fill="none" stroke="currentColor" stroke-width="1.8" />
              <path fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" d="M5 15V5a2 2 0 0 1 2-2h10" />
            </svg>
          }
        </button>
      </div>
    </div>

    <div class="agt-summary__body">
      @if (loading()) {
        <div class="agt-summary__skeleton" aria-hidden="true">
          <span></span><span></span><span></span>
        </div>
        <span class="agt-summary__sr-only" role="status">Generating summary…</span>
      } @else {
        <agt-stream-text [text]="content()" [streaming]="streaming()" [speed]="streamSpeed()" />
      }
    </div>
  `,
  styleUrl: './agt-summary.scss',
})
export class AgtSummary {
  readonly title = input('');
  readonly content = input('');
  readonly loading = input(false);
  readonly streaming = input(false);
  readonly streamSpeed = input<StreamSpeed>('smooth');

  readonly regenerate = output<void>();

  protected readonly copied = signal(false);

  protected copy(): void {
    navigator.clipboard?.writeText(this.content());
    this.copied.set(true);
    setTimeout(() => this.copied.set(false), 1200);
  }
}
